name: make-new-episode
on:
  schedule:
    - cron: '5 17 * * *'
  push:
jobs:
  build:
    name: make-episode
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: make-script
      run: |
        python script/make_episode.py
    - name: commit-episode
      run: |
        git config user.name "github-bot"
        git config user.email "terada@cmscom.jp"
        git add -A
        git commit -a -m "Create a new episode content"
        git push origin master
